server:
  port: 0

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}

spring:
  application:
    name: matching-service
  config:
    import: optional:configserver:http://127.0.0.1:8888
  cloud:
    config:
       name: service



  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 12341234

  jpa:
    hibernate:
      ddl-auto: update

    generate-ddl: true
    open-in-view: false
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        default_batch_fetch_size: 1000
    defer-datasource-initialization: true

logging:
  level:
    com.com.withsports: DEBUG
    org.hibernate.sql: DEBUG
#    org.hibernate.type: TRACE


# jpa query, parameter 로그 (p6spy)
decorator.datasource.p6spy:
  enable-logging: true



kafka:
  bootstrap:
    servers: 172.18.0.151:9092,172.18.0.152:9093,172.18.0.153:9094