server:
  port: 8000


eureka:
  client:
    allow-redirects: true
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

spring:
  application:
    name: api-gateway-service

  config:
    import: optional:configserver:http://127.0.0.1:8888


  cloud:
    config:
      name: bootstrap
    gateway:
      default-filters:
        - name: GlobalFilter
          args:
            baseMessage: Spring Cloud Gateway Global Filter
            preLogger: true
            postLogger: true
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins: "*"
            allowedMethods:
              - GET
              - POST
              - DELETE
              - PUT
              - OPTIONS
              - DELETE
              - PATCH
            allowedHeaders: '*'
            allow-credentials: false

      routes:
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/login
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/reissue
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/logout
            - Method=POST
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/auth/reissue
            - Method=GET
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}

#        연습삼아서 만들어본거
        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/success
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/oauth2/authorization/*
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/*/oauth2/code/*
          filters:
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}

        - id: user-service
          uri: lb://USER-SERVICE
          predicates:
            - Path=/user-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/user-service/(?<segment>.*),/$\{segment}

        - id: team-service
          uri: lb://TEAM-SERVICE
          predicates:
            - Path=/team-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/team-service/(?<segment>.*), /$\{segment}
            - name : RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 3
                key-resolver: "#{@tokenKeyResolver}"
        - id: matchingroom-service
          uri: lb://MATCHINGROOM-SERVICE
          predicates:
            - Path=/store-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/matchingroom-service/(?<segment>.*), /$\{segment}
            - name : RequestRateLimiter
              args:
                redis-rate-limiter.replenishRate: 3
                redis-rate-limiter.burstCapacity: 3
                key-resolver: "#{@tokenKeyResolver}"

        - id: matching-service
          uri: lb://MATCHING-SERVICE
          predicates:
            - Path=/matching-service/**
          filters:
            - AuthorizationHeaderFilter
            - RewritePath=/matching-service/(?<segment>.*), /$\{segment}




token:
  access-expired-time: 7200000
  refresh-expired-time: 604800000
  secret: A1B2C3D4E5F6G7H8I9J0K1L2M3N4O5P6Q7R8S9T0U1V2W3X4Y5Z6
  access-token-name: access-token
  refresh-token-name: refresh-token
